services:
  ui:
    image: musicians-ui
    build:
      context: ./UI
      args:
        CONFIG: production
    ports:
      - 4200:80
    depends_on:
      - api

  api:
    image: musicians-api
    build:
      context: ./API
      args:
        CONFIG: Release
    env_file:
      - .env
    environment:
      LASTFM_KEY: ${API_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION_STRING: "Server=db;Database=MusiciansDb;User=sa;Password=${DB_PASSWORD};"
    ports:
      - 7093:7093
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - .env
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - musicians-db:/var/opt/mssql

volumes:
  musicians-db: