services:
  ui:
    image: ${DOCKERHUB_USERNAME}/musicians-ui:latest
    ports:
      - 80:80
    environment:
      CONFIG: production
    depends_on:
      - api

  api:
    image: ${DOCKERHUB_USERNAME}/musicians-api:latest
    env_file:
      - .env
    environment:
      LASTFM_KEY: ${API_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION_STRING: "Server=db;Database=MusiciansDb;Port=5432;User Id=postgres;Password=${DB_PASSWORD};"
      APP_IP: ${APP_IP}
      APP_DNS: ${APP_DNS}
    ports:
      - 7093:7093
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: MusiciansDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - musicians-db:/var/lib/postgresql/data

volumes:
  musicians-db:
