name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Confirm docker-compose version
        run: docker-compose --version

      - name: Create .env file for docker-compose
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Build all services
        run: docker-compose build

      - name: Run containers
        run: docker-compose up -d

      - name: Show running containers
        run: docker-compose ps

      - name: Stop containers
        if: always()
        run: docker-compose down
