name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API container
        run: |
          docker build -t musicians-api ./API
          docker run -d --name api-container musicians-api

      - name: Build UI container
        run: |
          docker build -t musicians-ui ./UI
          docker run -d --name ui-container musicians-ui

      - name: Verify API container is running
        run: |
          docker ps -f name=api-container
          if [ $? -ne 0 ]; then
            echo "API container is not running"
            exit 1
          else
            echo "API container is running"
          fi

      - name: Verify UI container is running
        run: |
          docker ps -f name=ui-container
          if [ $? -ne 0 ]; then
            echo "UI container is not running"
            exit 1
          else
            echo "UI container is running"
          fi

      - name: Stop containers
        if: always()
        run: |
          docker stop api-container ui-container
          docker rm api-container ui-container
