name: Deploy API and UI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./API
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-api:${{ github.sha }}

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./UI
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-ui:${{ github.sha }}

  deploy:
    name: Deploy published images to EC2
    runs-on: ubuntu-latest
    needs: push-images

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create app folder on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p /home/ec2-user/app"

      - name: Upload docker-compose.yml
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/app/docker-compose.yml

      - name: Create .env on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > /home/ec2-user/app/.env
            echo "API_KEY=${{ secrets.API_KEY }}" >> /home/ec2-user/app/.env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> /home/ec2-user/app/.env
          EOF

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/app
            docker-compose pull || true
            docker-compose down
            docker-compose up -d
            docker ps
          EOF
