name: Push to DockerHub

on:
  push:
    branches:
      - main

jobs:
  dockerhub-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./API
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-api:${{ github.sha }}

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./UI
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-ui:${{ github.sha }}
