name: Push App to DockerHub

on:
  workflow_run:
    workflows: ['Provision AWS Infrastructure']
    types:
      - completed

jobs:
  push-images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    outputs:
      ec2_ip: ${{ steps.export.outputs.ec2_ip }}
      ec2_dns: ${{ steps.export.outputs.ec2_dns }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Terraform outputs
        id: export
        run: |
          echo "ec2_ip=${{ github.event.workflow_run.outputs.ec2_ip }}" >> $GITHUB_OUTPUT
          echo "ec2_dns=${{ github.event.workflow_run.outputs.ec2_dns }}" >> $GITHUB_OUTPUT

      - name: Generate UI environment.prod.ts
        run: ./scripts/generate-ui-env.sh ${{ steps.export.outputs.ec2_ip }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./API
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-api:${{ steps.tag_version.outputs.new_tag }}
          labels: |
            app=musicians-api

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./UI
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/musicians-ui:${{ steps.tag_version.outputs.new_tag }}
          labels: |
            app=musicians-ui
