name: Provision AWS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: AWS Infrastructure with Terraform
    runs-on: ubuntu-latest

    outputs:
      ec2_ip: ${{ steps.export.outputs.ec2_ip }}
      ec2_dns: ${{ steps.export.outputs.ec2_dns }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Export Terraform Outputs
        id: export
        run: |
          echo "ec2_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
          echo "ec2_dns=$(terraform output -raw instance_public_dns)" >> $GITHUB_OUTPUT
