name: Provision AWS Infrastructure

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infrastructure

      - name: Show Terraform Plan
        run: terraform show -no-color tfplan
        working-directory: ./infrastructure

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infrastructure/tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./infrastructure

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
        working-directory: ./infrastructure

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Update GitHub Repository Variables
        run: |
          ec2_ip=$(terraform output -raw instance_public_ip)
          ec2_dns=$(terraform output -raw instance_public_dns)

          echo "Setting EC2_IP and EC2_DNS as repository variables..."
          gh variable set EC2_IP --body "$ec2_ip"
          gh variable set EC2_DNS --body "$ec2_dns"
        working-directory: ./infrastructure
